<?php
/**
 * @file
 * Module file for miniOrange sso Module.
 */
?>
  <style>
    .mess_red{
      font-weight: bold;
      display: block;
      margin-top: 10px;
      color: red;
      background-color: rgba(251, 232, 0, 0.15);
      padding: 5px;
      border: solid 1px rgba(255, 0, 9, 0.36);
    }
    #edit-gluu-sso-customer-setup-button{
      background: #00d300 !important;
      color: black !important;
    }
    th {
      text-align: center !important;
    }
    /*td{
      border: 1px solid #00d300 !important;
    }*/
    .tabs li a{
      background-color:#00d300 !important;
    }
    ul.primary li.active a, ul.primary li.active a.active, ul.primary li.active a:active, ul.primary li.active a:visited{
      background-color:white !important;
    }
    #gluu-sso-general-setup, #gluu-sso-scopes-scripts-setup, #gluu-sso-gateway-form,#gluu-sso-testauthentication, #gluu-sso-workflow,#gluu-sso-config-form{
      border: 2px solid #00d300 !important;
      padding: 20px !important;
      border-radius: 5px !important;
    }
  </style>
<?php

function add_js_css_fonts() {
  drupal_add_js('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'gluu_sso') . '/files/js/scope-custom-script.js' );
  drupal_add_js( drupal_get_path('module', 'gluu_sso') . '/files/js/gluu_oxd_scripts.js' );
}
add_js_css_fonts() ;

?>

<?php
/**
 * Implements hook_menu().
 */
function gluu_sso_menu() {

  $items['admin/config/people/gluu_sso'] = array(
    'title' => 'Gluu SSO/ Gluu and social login configuration',
    'description' => 'Gluu SSO',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gluu_sso_general_setup'),
    'access arguments' => array('administer site configuration'),
    'file' => 'gluu_sso_general_setup.inc',
  );

  $items['admin/config/people/gluu_sso/general'] = array(
    'title' => 'General',
    'weight' => -5,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('gluu_sso_general_setup'),
    'file' => 'gluu_sso_general_setup.inc',
  );

  $items['admin/config/people/gluu_sso/scopes_scripts'] = array(
    'title' => 'Scopes and custom scripts',
    'weight' => -4,
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('gluu_sso_scopes_scripts_setup'),
    'file' => 'gluu_sso_scopes_scripts_setup_details.inc',
  );

  $items['admin/config/people/gluu_sso/config_form_setup'] = array(
    'title' => 'Gluu and social login config',
    'weight' => -3,
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('gluu_sso_config_form'),
    'file' => 'gluu_sso_config_form_setup.inc',
  );

  $items['admin/config/people/gluu_sso/testauthentication'] = array(
    'title' => 'Shortcode',
    'page_callback' => 'drupal_get_form',
    'weight' => -2,
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('gluu_sso_testauthentication'),
    'file' => 'gluu_sso_testauthentication.inc',
  );
  $items['admin/config/people/gluu_sso/how_it_works'] = array(
      'title' => 'Help & Troubleshooting',
      'weight' => -1,
      'type' => MENU_LOCAL_TASK,
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('gluu_sso_workflow'),
      'file' => 'gluu_sso_workflow.inc',
  );

  return $items;
}
/**
 * Implements hook_user_login_alter().
 */
function gluu_sso_form_user_login_alter(&$form, $form_state) {
  $sso_login_enabled = variable_get('gluu_sso_enable_login', FALSE);
  if (!empty($sso_login_enabled)) {
    array_unshift($form['#validate'], 'gluu_sso_login_validate');
  }
}

/**
 * Implements hook_user_login_block_alter().
 */

function gluu_sso_form_user_login_block_alter(&$form, &$form_state) {
if(isset($_GET['gluuOption'])){
  oxd_openid_login_validate();
}
  $form['miniorange_samlauth_login_link'] = array(
  );
  $form['markup_2'] = array(
      '#markup' =>login_html(),
      );
  $form['links']['#weight'] = 1;
}
function oxd_openid_load_login_script() {
  drupal_add_css(drupal_get_path('module', 'gluu_sso') . '/files/css/oxd_openid_style.css');
  drupal_add_css(drupal_get_path('module', 'gluu_sso') . '/files/css/bootstrap-social.css');
  drupal_add_css(drupal_get_path('module', 'gluu_sso') . '/files/css/bootstrap.min.css');
  drupal_add_css(drupal_get_path('module', 'gluu_sso') . '/files/css/font-awesome.min.css');
  drupal_add_css(drupal_get_path('module', 'gluu_sso') . '/files/css/font-awesome.css');
  ?>
  <script type="text/javascript">
    function oxdOpenIdLogin(app_name) {
      <?php
      global $base_url;
          if(isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off'){
              $http = "https://";
          } else {
              $http =  "http://";
          }
          if ( strpos($_SERVER['REQUEST_URI'],'wp-login.php') !== FALSE){
                  $redirect_url = $base_url . '/wp-login.php?gluuOption=getOxdSocialLogin&app_name=';

          }else{
                  $redirect_url = $http . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
                  if(strpos($redirect_url, '?') !== false) {
                      $redirect_url .= '&gluuOption=getOxdSocialLogin&app_name=';
                  } else {
                      $redirect_url .= '?gluuOption=getOxdSocialLogin&app_name=';
                  }
          }
      ?>
      window.location.href = '<?php echo $redirect_url; ?>' + app_name;
    }
  </script>
  <?php
}

function login_html(){
  $selected_theme = variable_get('oxd_openid_login_theme');
  $custom_scripts = variable_get('oxd_openid_custom_scripts');
  $appsConfigured = 0;
  foreach($custom_scripts as $custom_script){
    if(variable_get('oxd_openid_'.$custom_script['value'].'_enable') ){
      $appsConfigured = variable_get('oxd_openid_'.$custom_script['value'].'_enable');
    }
  }
  $spacebetweenicons = variable_get('oxd_login_icon_space');
  $customWidth = variable_get('oxd_login_icon_custom_width');
  $customHeight = variable_get('oxd_login_icon_custom_height');
  $customSize = variable_get('oxd_login_icon_custom_size');
  $customBackground = variable_get('oxd_login_icon_custom_color');
  $customTheme = variable_get('oxd_openid_login_custom_theme');
  $customTextofTitle = variable_get('oxd_openid_login_button_customize_text');
  $html ='';
  if( $appsConfigured ) {
    oxd_openid_load_login_script();
    $html.='
    <div class="oxd-openid-app-icons">
      <p>Connect with:</p>';

      $custom_scripts = variable_get('oxd_openid_custom_scripts');
      if($customTheme == 'default'){
        foreach($custom_scripts as $custom_script){
          if( variable_get('oxd_openid_'.$custom_script['value'].'_enable') ) {
            if($selected_theme == 'longbutton'){
              $html.='<a onClick="oxdOpenIdLogin('.$custom_script['value'].');" style="width:'.$customWidth.'px !important;padding-top:'.($customHeight-29).'px !important;padding-bottom:'.($customHeight-29).'px !important;margin-bottom:'.($spacebetweenicons-5).'px !important" class="btn btn-block btn-social btn-facebook  btn-custom-size login-button" >
              <i style="padding-top:'.($customHeight-35).'px !important" class="fa fa-facebook"></i>'.variable_get('oxd_openid_login_button_customize_text').' '.$custom_script['name'].'</a>';
             }
            else{
              $k = 'oxdOpenIdLogin("'.$custom_script['value'].'")';
                  $html.="<a onclick=' $k '>
                            <img
                              style='
                                      width:".$customSize."px !important;
                                      height:".$customSize."px !important;
                                      margin-left:".($spacebetweenicons-4)."px !important
                                    '
                              src='".$custom_script['image']."'
                              class='".$selected_theme." login-button'
                            />
                          </a>";
             }
          }
        }
      }
      if($customTheme == 'custom'){
        foreach($custom_scripts as $custom_script){
          if( variable_get('oxd_openid_'.$custom_script['value'].'_enable') ) {
            if($selected_theme == 'longbutton'){
              $html.='<a  onClick="oxdOpenIdLogin('.$custom_script['value'].');" style="width:'.$customWidth.'px !important;padding-top:'.($customHeight-29).'px !important;padding-bottom:'.($customHeight-29).'px !important;margin-bottom:'.($spacebetweenicons-5).'px !important;background:'."#".$customBackground.'!important" class="btn btn-block btn-social btn-facebook  btn-custom-size login-button" >
              <i style="padding-top:'.($customHeight-35).'px !important" class="fa fa-facebook"></i>
              '.variable_get('oxd_openid_login_button_customize_text').' '.$custom_script['name'].'</a>';
            }
            else{
              $html.='<a  onClick="oxdOpenIdLogin('.$custom_script['value'].');" title="'.$customTextofTitle .' '. $custom_script['name'].'">
              <i style="width:'.$customSize.'px !important;height:'.$customSize.'px !important;margin-left:'.($spacebetweenicons-4).'px !important;background:'."#".$customBackground.' !important;font-size:'.($customSize-16).'px !important;" class="fa fa-facebook custom-login-button '.$selected_theme.'" ></i></a>';
            }
          }
        }
      }
      $html.='<br>
    </div>
    <br>';
  } else {
    $html.='<div>No apps configured. Please contact your administrator.</div>';
  }
  return $html;
}

function oxd_openid_login_validate(){
  global $base_url;
  if( isset( $_REQUEST['gluuOption'] ) and strpos( $_REQUEST['gluuOption'], 'getOxdSocialLogin' ) !== false ) {
    $http = isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? "https://" : "http://";
    $parts = parse_url($http . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"]);
    parse_str($parts['query'], $query);
    $conf = variable_get('gluu_config');
    if(variable_get('oxd_id')){
      if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        if(!exec('netstat -aon |find/i "listening" |find "'.$conf['oxd_host_port'].'"')){
          echo "<script>
                  alert('Oxd server is not switched on.');window.location.href='".$base_url."';
               </script>";
          exit;
        }
      } else {
        if(!exec('netstat -tulpn | grep :'.$conf['oxd_host_port'])){
          echo "<script>
                  alert('Oxd server is not switched on.');window.location.href='".$base_url."';
               </script>";
          exit;
        }
      }
    }
    $get_authorization_url = new Get_authorization_url();
    $get_authorization_url->setRequestOxdId(variable_get('oxd_id'));
    $get_authorization_url->setRequestAcrValues([$_REQUEST['app_name']]);
    $get_authorization_url->request();
    header('Location: ' . $get_authorization_url->getResponseAuthorizationUrl());
    exit;
  }
  if(isset( $_REQUEST['gluuOption'] ) and strpos( $_REQUEST['gluuOption'], 'oxdOpenId' ) !== false ){
    $http = isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? "https://" : "http://";
    $parts = parse_url($http . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"]);
    parse_str($parts['query'], $query);
    $config_option = variable_get( 'gluu_config' );
    $conf = variable_get('gluu_config');
    $get_tokens_by_code = new Get_tokens_by_code();
    $get_tokens_by_code->setRequestOxdId(variable_get('oxd_id'));
    $get_tokens_by_code->setRequestCode($_REQUEST['code']);
    $get_tokens_by_code->setRequestState($_REQUEST['state']);
    $get_tokens_by_code->setRequestScopes($config_option["scope"]);
    $get_tokens_by_code->request();

    $get_tokens_by_code_array = $get_tokens_by_code->getResponseObject()->data->id_token_claims;

    setcookie( 'user_oxd_id_token', $get_tokens_by_code->getResponseIdToken());
    setcookie( 'user_oxd_access_token', $get_tokens_by_code->getResponseAccessToken());
    setcookie( 'session_states', $_REQUEST['session_state']);
    setcookie( 'states', $_REQUEST['state']);
    $get_user_info = new Get_user_info();
    $get_user_info->setRequestOxdId(variable_get('oxd_id'));
    $get_user_info->setRequestAccessToken($_COOKIE['user_oxd_access_token']);
    $get_user_info->request();
    $get_user_info_array = $get_user_info->getResponseObject()->data->claims;

    $reg_first_name = '';
    $reg_last_name = '';
    $reg_email = '';
    $reg_avatar = '';
    $reg_display_name = '';
    $reg_nikname = '';
    $reg_website = '';
    $reg_middle_name = '';
    $reg_country = '';
    $reg_city = '';
    $reg_region = '';
    $reg_gender = '';
    $reg_postal_code = '';
    $reg_fax = '';
    $reg_home_phone_number = '';
    $reg_phone_mobile_number = '';
    $reg_street_address = '';
    $reg_birthdate = '';
    if(!empty($get_user_info_array->website[0])){
      $reg_website = $get_user_info_array->website[0];
    }elseif(!empty($get_tokens_by_code_array->website[0])){
      $reg_website = $get_tokens_by_code_array->website[0];
    }
    if(!empty($get_user_info_array->nickname[0])){
      $reg_nikname = $get_user_info_array->nickname[0];
    }elseif(!empty($get_tokens_by_code_array->nickname[0])){
      $reg_nikname = $get_tokens_by_code_array->nickname[0];
    }
    if(!empty($get_user_info_array->name[0])){
      $reg_display_name = $get_user_info_array->name[0];
    }elseif(!empty($get_tokens_by_code_array->name[0])){
      $reg_display_name = $get_tokens_by_code_array->name[0];
    }
    if(!empty($get_user_info_array->given_name[0])){
      $reg_first_name = $get_user_info_array->given_name[0];
    }elseif(!empty($get_tokens_by_code_array->given_name[0])){
      $reg_first_name = $get_tokens_by_code_array->given_name[0];
    }
    if(!empty($get_user_info_array->family_name[0])){
      $reg_last_name = $get_user_info_array->family_name[0];
    }elseif(!empty($get_tokens_by_code_array->family_name[0])){
      $reg_last_name = $get_tokens_by_code_array->family_name[0];
    }
    if(!empty($get_user_info_array->middle_name[0])){
      $reg_middle_name = $get_user_info_array->middle_name[0];
    }elseif(!empty($get_tokens_by_code_array->middle_name[0])){
      $reg_middle_name = $get_tokens_by_code_array->middle_name[0];
    }
    if(!empty($get_user_info_array->email[0])){
      $reg_email = $get_user_info_array->email[0];
    }elseif(!empty($get_tokens_by_code_array->email[0])){
      $reg_email = $get_tokens_by_code_array->email[0];
    }
    if(!empty($get_user_info_array->country[0])){
      $reg_country = $get_user_info_array->country[0];
    }elseif(!empty($get_tokens_by_code_array->country[0])){
      $reg_country = $get_tokens_by_code_array->country[0];
    }
    if(!empty($get_user_info_array->gender[0])){
      if(!empty($get_user_info_array->gender[0] == 'male')){
        $reg_gender = '1';
      }else{
        $reg_gender = '2';
      }

    }elseif(!empty($get_tokens_by_code_array->gender[0])){
      if(!empty($get_tokens_by_code_array->gender[0] == 'male')){
        $reg_gender = '1';
      }else{
        $reg_gender = '2';
      }
    }
    if(!empty($get_user_info_array->locality[0])){
      $reg_city = $get_user_info_array->locality[0];
    }elseif(!empty($get_tokens_by_code_array->locality[0])){
      $reg_city = $get_tokens_by_code_array->locality[0];
    }
    if(!empty($get_user_info_array->postal_code[0])){
      $reg_postal_code = $get_user_info_array->postal_code[0];
    }elseif(!empty($get_tokens_by_code_array->postal_code[0])){
      $reg_postal_code = $get_tokens_by_code_array->postal_code[0];
    }
    if(!empty($get_user_info_array->phone_number[0])){
      $reg_home_phone_number = $get_user_info_array->phone_number[0];
    }elseif(!empty($get_tokens_by_code_array->phone_number[0])){
      $reg_home_phone_number = $get_tokens_by_code_array->phone_number[0];
    }
    if(!empty($get_user_info_array->phone_mobile_number[0])){
      $reg_phone_mobile_number = $get_user_info_array->phone_mobile_number[0];
    }elseif(!empty($get_tokens_by_code_array->phone_mobile_number[0])){
      $reg_phone_mobile_number = $get_tokens_by_code_array->phone_mobile_number[0];
    }
    if(!empty($get_user_info_array->picture[0])){
      $reg_avatar = $get_user_info_array->picture[0];
    }elseif(!empty($get_tokens_by_code_array->picture[0])){
      $reg_avatar = $get_tokens_by_code_array->picture[0];
    }
    if(!empty($get_user_info_array->street_address[0])){
      $reg_street_address = $get_user_info_array->street_address[0];
    }elseif(!empty($get_tokens_by_code_array->street_address[0])){
      $reg_street_address = $get_tokens_by_code_array->street_address[0];
    }
    if(!empty($get_user_info_array->birthdate[0])){
      $reg_birthdate = $get_user_info_array->birthdate[0];
    }elseif(!empty($get_tokens_by_code_array->birthdate[0])){
      $reg_birthdate = $get_tokens_by_code_array->birthdate[0];
    }
    if(!empty($get_user_info_array->region[0])){
      $reg_region = $get_user_info_array->region[0];
    }elseif(!empty($get_tokens_by_code_array->region[0])){
      $reg_region = $get_tokens_by_code_array->region[0];
    }

    $username = '';
    if(!empty($get_user_info->getResponsePreferredUsername())){
      $username = $get_user_info->getResponsePreferredUsername().'6';
    }
    else {
      $email_split = explode("@", $reg_email);
      $username = $email_split[0].'6';
    }
    $account = user_external_load($username);
    if (!$account) {
      // Register this new user.
      $userinfo = array(
          'name' => $username.'6',
          'pass' => user_password(),
          'mail' => $reg_email,
          'init' => $reg_email,
          'status' => 1,
          'access' => REQUEST_TIME,
      );
      $account = user_save(drupal_anonymous_user(), $userinfo);
      // Terminate if an error occurred during user_save().
      if (!$account) {
        drupal_set_message(t("Error saving user account."), 'error');
        return;
      }
      user_set_authmaps($account, array("authname_gluu_sso" => $username));
    }

    // Log user in.
    $form_state['uid'] = $account->uid;
    user_login_submit(array(), $form_state);
    drupal_goto();

  }
}