<?php
	/**
	 * @file
	 * Gluu_sso_get_authorization_url class .
	 */
	require_once 'Client_OXD_RP.php';
	
	class Gluu_sso_get_authorization_url extends Gluu_sso_client_OXD_RP
	{
		/**
		 * @var string $request_oxd_id This parameter you must get after registration site in gluu-server
		 */
		private $request_oxd_id = null;
		/**
		 * @var string $request_oxd_id This parameter you must get after registration site in gluu-server
		 */
		private $request_scope = null;
		/**
		 * @var string $request_prompt This parameter need use when you use many authentication
		 */
		private $request_prompt = null;
		/**
		 * @var array $request_acr_values It is gluu-server login parameter type
		 */
		private $request_acr_values = null;
                /**
                * @var string $request_access_token     access token for each request
                */
                private $request_protection_access_token;
		
		/**
		 * It is authorization url to gluu server.
		 * After getting this parameter go to that url and you can login to gluu server, and get response about your users
		 * @var string $response_authorization_url
		 */
		private $response_authorization_url;
		
		/**
		 * Constructor
		 * @return  void
		 */
		public function __construct()
		{
			parent::__construct(); // TODO: Change the autogenerated stub
		}
		
		/**
		 * @return NULL
		 */
		public function getRequestScope()
		{
			return $this->request_scope;
		}
		
		/**
		 * @param NULL $request_scope
		 */
		public function setRequestScope($request_scope)
		{
			$this->request_scope = $request_scope;
		}
		
		/**
		 * @return string
		 */
		public function getRequestPrompt()
		{
			return $this->request_prompt;
		}
		
		/**
		 * @param string $request_prompt
		 */
		public function setRequestPrompt($request_prompt)
		{
			$this->request_prompt = $request_prompt;
		}
		
		/**
		 * @return string
		 */
		public function getRequestOxdId()
		{
			return $this->request_oxd_id;
		}
		
		/**
		 * @param string $request_oxd_id
		 * @return void
		 */
		public function setRequestOxdId($request_oxd_id)
		{
			$this->request_oxd_id = $request_oxd_id;
		}
		
		/**
		 * @return array
		 */
		public function getRequestAcrValues()
		{
			return $this->request_acr_values;
		}
		
		/**
		 * @param array $request_acr_values
		 * @return void
		 */
		public function setRequestAcrValues($request_acr_values)
		{
			$this->request_acr_values = $request_acr_values;
		}
		
		/**
		 * @return string
		 */
		public function getResponseAuthorizationUrl()
		{
			$this->response_authorization_url = $this->getResponseData()->authorization_url;
			
			return $this->response_authorization_url;
		}
                
                /**
                 * @return string
                 */
                function getRequest_protection_access_token() {
                    return $this->request_protection_access_token;
                }

                /**
                 * @param string $request_protection_access_token
                 * @return void
                 */
                function setRequest_protection_access_token($request_protection_access_token) {
                    $this->request_protection_access_token = $request_protection_access_token;
                }
                
		
		/**
		 * Protocol command to oXD server
		 * @return void
		 */
		public function setCommand()
		{
			$this->command = 'get_authorization_url';
		}
		
		/**
		 * Protocol parameter to oXD server
		 * @return void
		 */
		public function setParams()
		{
			$this->params = array(
				"oxd_id" => $this->getRequestOxdId(),
				"acr_values" => $this->getRequestAcrValues(),
				"prompt" => $this->getRequestPrompt(),
				"scope" => $this->getRequestScope(),
                                "protection_access_token" => $this->getRequest_protection_access_token()
			);
		}
		
	}
